---
- name: Create privileged folders
  become: yes
  file:
      path: "{{item}}"
      state: directory
      mode: 0755
      recurse: yes
  loop:
  - "{{jdk_destination}}"

- name: Download Azul JDK 10 Tarball
  become: no
  get_url:
      url: "https://cdn.azul.com/zulu/bin/zulu{{jdk_azul_jdk_10_build}}-jdk10-linux_x64.tar.gz"
      dest: "{{ansible_user_dir}}/{{jdk_download_directory}}/azul-jdk-{{jdk_azul_jdk_10_build}}.tar.gz"
      mode: 0444
  when: jdk_azul_jdk_10_install

- name: Uncompress Azul JDK 10 Tarball
  become: yes
  unarchive:
      src: "{{ansible_user_dir}}/{{jdk_download_directory}}/azul-jdk-{{jdk_azul_jdk_10_build}}.tar.gz"
      dest: "{{jdk_destination}}"
      copy: no
      owner: "{{ansible_user_uid}}"
      group: "{{ansible_user_gid}}"
      mode: 0555
      creates: "{{jdk_destination}}//zulu{{jdk_azul_jdk_10_build}}-jdk10-inux_x64/LICENSE"
  when: jdk_azul_jdk_10_install

- name: Test Azul JDK 10 
  become: no
  command: "{{jdk_destination}}//zulu{{jdk_azul_jdk_10_build}}-jdk10-linux_x64/bin/java -version"
  when: jdk_azul_jdk_10_install

- name: Create Softlink To Azul JDK 10 
  become: yes
  file:
      src: "{{jdk_destination}}//zulu{{jdk_azul_jdk_10_build}}-jdk10-linux_x64"
      dest: "{{jdk_destination}}/{{jdk_azul_jdk_10_link_destination}}"
      owner: "{{ansible_user_uid}}"
      group: "{{ansible_user_gid}}"
      state: link
  when: jdk_azul_jdk_10_install

- name: Download Azul JDK 9 Tarball
  become: no
  get_url:
      url: "http://cdn.azul.com/zulu/bin/zulu{{jdk_azul_jdk_9_build}}-jdk{{jdk_azul_jdk_9_version}}-linux_x64.tar.gz"
      dest: "{{ansible_user_dir}}/{{jdk_download_directory}}/azul-jdk-{{jdk_azul_jdk_9_version}}.tar.gz"
      mode: 0444
  when: jdk_azul_jdk_9_install

- name: Uncompress Azul JDK 9 Tarball
  become: yes
  unarchive:
      src: "{{ansible_user_dir}}/{{jdk_download_directory}}/azul-jdk-{{jdk_azul_jdk_9_version}}.tar.gz"
      dest: "{{jdk_destination}}"
      copy: no
      owner: "{{ansible_user_uid}}"
      group: "{{ansible_user_gid}}"
      mode: 0555
      creates: "{{jdk_destination}}//zulu{{jdk_azul_jdk_9_build}}-jdk{{jdk_azul_jdk_9_version}}-linux_x64/LICENSE"
  when: jdk_azul_jdk_9_install

- name: Test Azul JDK 9
  become: no
  command: "{{jdk_destination}}//zulu{{jdk_azul_jdk_9_build}}-jdk{{jdk_azul_jdk_9_version}}-linux_x64/bin/java -version"
  when: jdk_azul_jdk_9_install

- name: Create Softlink To Azul JDK 9
  become: yes
  file:
      src: "{{jdk_destination}}//zulu{{jdk_azul_jdk_9_build}}-jdk{{jdk_azul_jdk_9_version}}-linux_x64"
      dest: "{{jdk_destination}}/{{jdk_azul_jdk_9_link_destination}}"
      owner: "{{ansible_user_uid}}"
      group: "{{ansible_user_gid}}"
      state: link
  when: jdk_azul_jdk_9_install

- name: Set Interactive Environments To Use Default JDK
  become: yes
  template:
      src: "templates/default-jdk-environment.sh.j2"
      dest: "/etc/profile.d/default-jdk-environment.sh"
      owner: "{{ansible_user_uid}}"
      group: "{{ansible_user_gid}}"
      mode: 0555

- name: Set Non-Interactive Environments To Use Default JDK
  become: yes
  lineinfile:
      dest: /etc/environment
      line: '{{item}}'
  loop:
  - "JAVA_HOME={{jdk_destination}}/{{jdk_azul_jdk_8_link_destination}}"
  - "JDK_8_HOME={{jdk_destination}}/{{jdk_azul_jdk_8_link_destination}}"
  - "JDK_9_HOME={{jdk_destination}}/{{jdk_azul_jdk_9_link_destination}}"
  - "JDK_10_HOME={{jdk_destination}}/{{jdk_azul_jdk_10_link_destination}}"

- name: Download Azul JDK 8 Tarball
  become: no
  get_url:
      url: "http://cdn.azul.com/zulu/bin/zulu{{jdk_azul_jdk_8_build}}-jdk{{jdk_azul_jdk_8_version}}-linux_x64.tar.gz"
      dest: "{{ansible_user_dir}}/{{jdk_download_directory}}/azul-jdk-{{jdk_azul_jdk_8_version}}.tar.gz"
      mode: 0444
  when: jdk_azul_jdk_8_install

- name: Uncompress Azul JDK 8 Tarball
  become: yes
  unarchive:
      src: "{{ansible_user_dir}}/{{jdk_download_directory}}/azul-jdk-{{jdk_azul_jdk_8_version}}.tar.gz"
      dest: "{{jdk_destination}}"
      copy: no
      owner: "{{ansible_user_uid}}"
      group: "{{ansible_user_gid}}"
      mode: 0555
      creates: "{{jdk_destination}}//zulu{{jdk_azul_jdk_8_build}}-jdk{{jdk_azul_jdk_8_version}}-linux_x64/LICENSE"
  when: jdk_azul_jdk_8_install

- name: Test Azul JDK 8
  become: no
  command: "{{jdk_destination}}//zulu{{jdk_azul_jdk_8_build}}-jdk{{jdk_azul_jdk_8_version}}-linux_x64/bin/java -version"
  when: jdk_azul_jdk_8_install

- name: Create Softlink To Azul JDK 8
  become: yes
  file:
      src: "{{jdk_destination}}//zulu{{jdk_azul_jdk_8_build}}-jdk{{jdk_azul_jdk_8_version}}-linux_x64"
      dest: "{{jdk_destination}}/{{jdk_azul_jdk_8_link_destination}}"
      owner: "{{ansible_user_uid}}"
      group: "{{ansible_user_gid}}"
      state: link
  when: jdk_azul_jdk_8_install

